---
title: ""
message: false
warning: false
---

# Packages
```{r}
library(gsheet)
library(dplyr)
library(tidyverse)
```

# Pliman

Utilizamos este script para quantificar a severidade da mancha-amarela na folha. Os valores obtidos foram hospedados na nuvem e importados na seção seguinte.
```{r, echo=TRUE, eval=FALSE}

s2 <- image_import("fig/s.jpeg")
h <- readRDS("fig/my_paletteh.rds")
b <- readRDS("fig/my_palette_b.rds")

pliman <- measure_disease(
  pattern = "img_",
  dir_original = "image/originals" ,
  dir_processed = "image/processed",
  save_image = TRUE,
  img_healthy = h,
  img_symptoms = s2,
  img_background = b,
  verbose = FALSE,
  plot = FALSE
)

severity = data.frame(pliman$severity)
#writexl::write_xlsx(severity,"image/data/real_severity.xlsx")
```

# Data importation
```{r}
#sad = gsheet2tbl("https://docs.google.com/spreadsheets/d/1hLxH3CzhtBC1InN_rmTmll96m5z4U1SsWytDi2FDuIc/edit?usp=sharing")

sad = readxl::read_xlsx("data/sad.xlsx")

sad$real = as.numeric(sad$real)
```

# Filtering
```{r}
sad2 = sad %>% 
  filter(!rater %in% c("10","3","31","33",
                     "34", "36","24", 
                    '20',"15", "38"))
```

```{r}
sad2 %>% 
  filter(!real > 86) %>% 
  summarise(
    max = max(real)
  )
```

# Raters estimation
```{r}
sad2 %>% 
  filter(!is.na(rater)) %>% 
  ggplot(aes(x = real, y = new)) +
  geom_point() +
  facet_wrap(~ rater, ncol = 5) +
  scale_x_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, 10),
    oob = scales::squish,    # em vez de descartar >100, “corta” em 100
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, 10),
    oob = scales::squish,
    expand = c(0, 0)
  )+
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "solid")
```

```{r}

sad2 = sad2 %>% 
  filter(!is.na(rater))

```

# CCC's Lin

## With SAD
```{r}
ccc <- epiR :: epi.ccc(sad2$real,sad2$new)
ccc.result <- ccc $ rho.c 
ccc.result 

```

```{r}
Cb <- ccc$C.b
Cb

```

```{r}
r <- ccc$rho.c[,1]/ccc$C.b
r
```

## Without SAD
```{r}
ccc <- epiR :: epi.ccc(sad2$real,sad2$unaided)
ccc.result <- ccc $ rho.c 
ccc.result 

```

```{r}
Cb <- ccc$C.b
Cb

```

```{r}

r <- ccc$rho.c[,1]/ccc$C.b
r
```

## By raters
```{r}
sad_long <- sad2 %>%
  group_by(position, rater) %>%
  mutate(
    error_unaided = real - unaided,
    error_new     = real - new
  ) %>%
  ungroup() %>%
  pivot_longer(
    cols = starts_with("error_"),
    names_to = "SAD_type",
    values_to = "error"
  ) %>%
  mutate(
    SAD_type = case_when(
      SAD_type == "error_unaided" ~ "unaided",
      SAD_type == "error_new"     ~ "new"
    )
  )


sad_long2 <- sad_long %>%
  pivot_longer(
    cols = c(unaided, new),   
    names_to = "method",       
    values_to = "estimated"        
  ) %>%
  select(rater, position, real, method, estimated)
```

```{r}

library(DescTools)


stats_data = sad_long2 %>% 
  group_by(method, rater) %>% 
  summarise(ccc = CCC(estimated, real)$rho.c$est,
            r = cor(estimated, real),
            cb = CCC(estimated, real)$C.b,
            ccc_lower = CCC(estimated, real)$rho.c$lwr.ci,
            ccc_upper = CCC(estimated, real)$rho.c$upr.ci,
            s.shift = CCC(estimated, real)$s.shift,
            l.shift = CCC(estimated, real)$l.shift)
stats_data
```

# Intraclass Correlation Coefficient

## With SAD

```{r}
sad3 = sad2 %>%
  dplyr::select(real,rater,new) %>% 
  filter(!is.na(new))


sad2_wide <- sad3 %>%
  pivot_wider(
    id_cols = c(real),
    names_from = rater,
    values_from = new
  )

```

```{r}
library(epiR)

epi.occc(sad2_wide, na.rm = FALSE, pairs = TRUE)

```

```{r}
library(psych)

ic = ICC(sad2_wide)
knitr::kable(ic$results[1:2])

```

```{r}
library(irr)

icc(sad2_wide, "oneway")
```

## Without SAD
```{r}
sad3 = sad2 %>%
  dplyr::select(real,rater,unaided) %>% 
  filter(!is.na(unaided))


sad2_wide <- sad3 %>%
  pivot_wider(
    id_cols = c(real),
    names_from = rater,
    values_from = unaided
  )

```

```{r}
library(epiR)

epi.occc(sad2_wide, na.rm = FALSE, pairs = TRUE)

```

```{r}
library(psych)

ic = ICC(sad2_wide)
knitr::kable(ic$results[1:2])

```

```{r}
library(irr)

icc(sad2_wide, "oneway")
```

# Plots
```{r}
library(dplyr)
library(tidyr)

sad_long <- sad2 %>%
  group_by(position, rater) %>%
  mutate(
    error_unaided = real - unaided,
    error_new     = real - new
  ) %>%
  ungroup() %>%
  pivot_longer(
    cols = starts_with("error_"),
    names_to = "SAD_type",
    values_to = "error"
  ) %>%
  mutate(
    SAD_type = case_when(
      SAD_type == "error_unaided" ~ "Sem auxílio",
      SAD_type == "error_new"     ~ "Com auxílio"
    )
  )

library(ggthemes)

cores_metodo <- c(
  "Com auxílio"    = "#7FBF7B",
  "Sem auxílio"    = "#A6764D",
  "Antigo" = "steelblue")

error_estimated_ca = sad_long%>% 
  filter(!SAD_type == "Antigo") %>% 
  filter(SAD_type == "Com auxílio") %>%
  filter(!real > 86) %>% 
  ggplot(aes(real,error))+
  geom_point(aes(colour = SAD_type),size = 2)+
  geom_hline(yintercept = 0, color ="black", linetype = "solid")+
  geom_smooth(se = F, method = "loess", color = "tan2")+
  xlim(0,100)+
  #scale_color_colorblind()+
  scale_colour_manual(values = cores_metodo) +
  theme_few()+
  #scale_color_manual()
  labs(x = " ",
       y = "Erro absoluto")+
  theme(legend.position = "none",
        strip.background = element_blank(),
        strip.text = element_text(size = 14, face = "bold"),
        axis.text.x = element_blank())+
  facet_wrap(~SAD_type, ncol = 1)

error_estimated_sa = sad_long%>% 
  filter(!SAD_type == "Antigo") %>% 
  filter(SAD_type == "Sem auxílio") %>% 
  filter(!real > 86) %>% 
  ggplot(aes(real,error))+
  geom_point(aes(colour = SAD_type),size = 2)+
  geom_hline(yintercept = 0, color ="black", linetype = "solid")+
  geom_smooth(se = F, method = "loess", color = "tan2")+
  xlim(0,100)+
  #scale_color_colorblind()+
  scale_colour_manual(values = cores_metodo) +
  theme_few()+
  #scale_color_manual()
  labs(x = "",
       y = "")+
  theme(legend.position = "none",
        strip.background = element_blank(),
        strip.text = element_text(size = 14, face = "bold"),
        axis.text.x = element_blank())+
  facet_wrap(~SAD_type, ncol = 1)
```


```{r}
library(ggplot2)
library(dplyr)
library(ggthemes)
library(scales)
library(cowplot)

sad_long2 <- sad_long %>%
  pivot_longer(
    cols = c(unaided, new),   # colunas que você quer empilhar
    names_to = "method",           # nova coluna que identifica o tipo de estimativa
    values_to = "estimated"        # nova coluna com os valores numéricos
  ) %>%
  select(rater, position, real, method, estimated) %>% 
   mutate(
    method = case_when(
      method == "unaided" ~ "Sem auxílio",
      method == "new"     ~ "Com auxílio"
    ))


cores_metodo <- c(
  "Com auxílio"    = "#7FBF7B",
  "Sem auxílio"    = "#A6764D",
  "Antigo" = "steelblue")



CCC  <- 0.91
vies <- 0.98
prec <- 0.93


lab <- paste0(
  "CCC = ", number(CCC, accuracy = 0.01, decimal.mark = ","),
  "\nViés = ", number(vies, accuracy = 0.01, decimal.mark = ","),
  "\nPrecisão = ", number(prec, accuracy = 0.01, decimal.mark = ",")
)

estimated_ca <- sad_long2 %>%
  filter(method == "Com auxílio", !(real > 86)) %>%
  ggplot(aes(x = real, y = estimated)) +
  geom_jitter(aes(colour = method), width = 0.4) +
  scale_x_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, 20),
    oob = scales::squish,
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, 20),
    oob = scales::squish,
    expand = c(0, 0)
  ) +
  scale_colour_manual(values = cores_metodo) +
  geom_abline(slope = 1, intercept = 0, color = "tan2",
              linetype = "solid", size = 1.4) +
  facet_wrap(~method, ncol = 1) +
  theme_few() +
  labs(x = "Severidade real (%)",
       y = "Severidade estimada (%)",
       title = "Com escala") +
  theme(
    strip.text = element_blank(),
    legend.position= "none",
    plot.margin    = margin(10, 10, 10, 10),
    plot.title = element_text(hjust = 0.5, face = "bold")) +
  annotate(
    "text",
    x = -Inf, y = Inf,
    label = lab,
    hjust = -0.05,   
    vjust = 1.1,     
    size = 3.5,
    fontface = "bold",
    lineheight = 1.05
  ) +
  coord_cartesian(clip = "off")+
  coord_fixed()

estimated_ca
```

```{r}


CCC  <- 0.83
vies <- 0.98
prec <- 0.84

lab <- paste0(
  "CCC = ", number(CCC, accuracy = 0.01, decimal.mark = ","),
  "\nViés = ", number(vies, accuracy = 0.01, decimal.mark = ","),
  "\nPrecisão = ", number(prec, accuracy = 0.01, decimal.mark = ",")
)

estimated_sa <- sad_long2 %>%
  filter(method == "Sem auxílio", !(real > 86)) %>%
  ggplot(aes(x = real, y = estimated)) +
  geom_jitter(aes(colour = method), width = 0.4) +
  scale_x_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, 20),
    oob = scales::squish,
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, 20),
    oob = scales::squish,
    expand = c(0, 0)
  ) +
  scale_colour_manual(values = cores_metodo) +
  geom_abline(slope = 1, intercept = 0,
              color = "tan2", linetype = "solid", size = 1.4) +
  facet_wrap(~method, ncol = 1) +
  theme_few() +
  labs(x = "",
       y = "Severidade estimada (%)",
       title = "Sem escala") +
  theme(
    strip.text      = element_blank(),
    axis.text.x =  element_blank(),
    legend.position = "none",
    plot.margin     = margin(10, 10, 10, 10),
    plot.title = element_text(hjust = 0.5, face = "bold")) +
  annotate(
    "text",
    x = -Inf, y = Inf,
    label = lab,
    hjust = -0.05, 
    vjust = 1.1,     
    size = 3.5,
    fontface = "bold",
    lineheight = 1.05
  ) +
  coord_cartesian(clip = "off")+
  coord_fixed()  

estimated_sa

```

```{r}

library(patchwork)

#layout = (error_estimated_ca/estimated_ca)|(error_estimated_sa/estimated_sa)
layout = (estimated_sa)/(estimated_ca)

  layout &
  theme(plot.tag = element_text(face = "bold", size = 12))

ggsave("fig/erro_real_estimado.png", dpi =600, height = 8, width = 8)
```
